AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2.0
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Max: 120

Layout/LineLength:
  Exclude:
    - 'spec/curlify_spec.rb'
